import { Video, Doc, Prompt } from "@/types";

export const mockVideos: Video[] = [
  {
    id: "v1",
    title: "Como a IA está transformando o futuro do trabalho",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnail_url: "",
    status: "approved",
    submitted_by: "João Silva",
    created_at: "2024-08-20T10:00:00Z",
  },
  {
    id: "v2",
    title: "Introdução ao Prompt Engineering — do básico ao avançado",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnail_url: "",
    status: "approved",
    submitted_by: "Maria Oliveira",
    created_at: "2024-08-19T14:30:00Z",
  },
  {
    id: "v3",
    title: "IA generativa: tendências e possibilidades para 2025",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnail_url: "",
    status: "approved",
    submitted_by: "Pedro Santos",
    created_at: "2024-08-18T09:15:00Z",
  },
  {
    id: "v4",
    title: "Automação com LLMs — criando agentes inteligentes",
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnail_url: "",
    status: "approved",
    submitted_by: "Ana Costa",
    created_at: "2024-08-17T16:45:00Z",
  },
];

export const mockDocs: Doc[] = [
  {
    id: "d1",
    title: "Guia completo de criação de prompts",
    cover_url: "",
    file_url: "#",
    status: "approved",
    submitted_by: "Maria Oliveira",
    created_at: "2024-08-20T11:00:00Z",
  },
  {
    id: "d2",
    title: "RAG na prática",
    cover_url: "",
    file_url: "#",
    status: "approved",
    submitted_by: "Carlos Lima",
    created_at: "2024-08-19T13:00:00Z",
  },
  {
    id: "d3",
    title: "Fine-tuning de modelos",
    cover_url: "",
    file_url: "#",
    status: "approved",
    submitted_by: "Juliana Costa",
    created_at: "2024-08-18T10:30:00Z",
  },
  {
    id: "d4",
    title: "Agentes autônomos com LangChain",
    cover_url: "",
    file_url: "#",
    status: "approved",
    submitted_by: "Rafael Souza",
    created_at: "2024-08-17T15:00:00Z",
  },
  {
    id: "d5",
    title: "Visão computacional com IA",
    cover_url: "",
    file_url: "#",
    status: "approved",
    submitted_by: "Fernanda Alves",
    created_at: "2024-08-16T12:00:00Z",
  },
  {
    id: "d6",
    title: "NLP avançado — transformers",
    cover_url: "",
    file_url: "#",
    status: "approved",
    submitted_by: "Thiago Nunes",
    created_at: "2024-08-15T09:00:00Z",
  },
  {
    id: "d7",
    title: "IA na medicina — casos reais",
    cover_url: "",
    file_url: "#",
    status: "approved",
    submitted_by: "Beatriz Martins",
    created_at: "2024-08-14T14:00:00Z",
  },
  {
    id: "d8",
    title: "Segurança em sistemas de IA",
    cover_url: "",
    file_url: "#",
    status: "approved",
    submitted_by: "Lucas Ferreira",
    created_at: "2024-08-13T11:30:00Z",
  },
  {
    id: "d9",
    title: "Deploy de modelos em produção",
    cover_url: "",
    file_url: "#",
    status: "approved",
    submitted_by: "Camila Rocha",
    created_at: "2024-08-12T16:00:00Z",
  },
];

export const mockPrompts: Prompt[] = [
  {
    id: "p1",
    title: "Prompt avançado para análise de dados",
    cover_url: "",
    content:
      "Você é um analista de dados especialista. Analise os dados fornecidos e produza: 1) Resumo executivo; 2) Principais insights; 3) Anomalias detectadas; 4) Recomendações estratégicas. Formate a resposta em seções claras com bullet points.",
    status: "approved",
    submitted_by: "Pedro Santos",
    created_at: "2024-08-20T08:00:00Z",
  },
  {
    id: "p2",
    title: "Gerador de copy para marketing",
    cover_url: "",
    content:
      "Atue como um copywriter especialista em marketing digital. Crie 5 variações de copy para [produto/serviço], focando em [benefício principal]. Use gatilhos mentais de urgência e prova social. Tom: [formal/informal]. CTA claro no final.",
    status: "approved",
    submitted_by: "Ana Costa",
    created_at: "2024-08-19T10:00:00Z",
  },
  {
    id: "p3",
    title: "Revisor de código profissional",
    cover_url: "",
    content:
      "Você é um engenheiro sênior revisando código. Para o código fornecido, analise: bugs potenciais, performance, segurança, legibilidade e boas práticas. Sugira melhorias concretas com exemplos de código corrigido.",
    status: "approved",
    submitted_by: "Carlos Lima",
    created_at: "2024-08-18T12:00:00Z",
  },
  {
    id: "p4",
    title: "Criador de plano de negócios",
    cover_url: "",
    content:
      "Baseado na ideia de negócio fornecida, crie um plano completo incluindo: análise de mercado, modelo de receita, custos iniciais, estratégia de marketing, riscos e mitigações, projeções para 12 meses.",
    status: "approved",
    submitted_by: "Juliana Costa",
    created_at: "2024-08-17T14:00:00Z",
  },
  {
    id: "p5",
    title: "Assistente de escrita acadêmica",
    cover_url: "",
    content:
      "Atue como professor universitário. Revise o texto acadêmico fornecido melhorando: estrutura argumentativa, clareza, coerência, referências e formatação ABNT. Mantenha a voz original do autor.",
    status: "approved",
    submitted_by: "Rafael Souza",
    created_at: "2024-08-16T09:00:00Z",
  },
  {
    id: "p6",
    title: "Gerador de ideias criativas",
    cover_url: "",
    content:
      "Você é um diretor criativo com 20 anos de experiência. Para o tema [X], gere 10 ideias inovadoras e inesperadas. Para cada ideia: explique o conceito em 2 linhas, o diferencial competitivo e como executar.",
    status: "approved",
    submitted_by: "Fernanda Alves",
    created_at: "2024-08-15T11:00:00Z",
  },
];

export const mockPending = [
  {
    id: "pend1",
    type: "video" as const,
    title: "Como a IA está transformando o futuro",
    thumbnail_url: "",
    submitted_by: "João Silva",
    submitted_ago: "há 2 horas",
    status: "pending" as const,
  },
  {
    id: "pend2",
    type: "doc" as const,
    title: "Guia completo de criação de prompts",
    thumbnail_url: "",
    submitted_by: "Maria Oliveira",
    submitted_ago: "há 4 horas",
    status: "pending" as const,
  },
  {
    id: "pend3",
    type: "prompt" as const,
    title: "Prompt avançado para análise de dados",
    thumbnail_url: "",
    submitted_by: "Pedro Santos",
    submitted_ago: "há 6 horas",
    status: "pending" as const,
  },
  {
    id: "pend4",
    type: "video" as const,
    title: "IA generativa: tendências para 2025",
    thumbnail_url: "",
    submitted_by: "Juliana Costa",
    submitted_ago: "há 8 horas",
    status: "pending" as const,
  },
];
